name: Deploy to GitHub Pages
# Run workflow on every push to the master branch
on:
  push:
    branches: [ main ]
    
jobs:
  deploy-to-github-pages:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    # Setup dotnet on the remote machine
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    
    # publishes Blazor project to the release-folder
    - name: Publish .NET Core Project
      run: dotnet publish DataforgedGen.csproj -c Release -o release --nologo
      
    # Commit wwwroot folder to gh-pages branch
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.4.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: release/wwwroot      
